spring.application.name=StudentJPA

#spring.h2.console.enabled=true

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#Hold dataen i databasen: hvis du ikke vil miste data
spring.jpa.hibernate.ddl-auto=update

#Starter forfra: når du designer databasen.
#spring.jpa.hibernate.ddl-auto=create-drop

#Viser hvilke sql queires et kode laver i terminal. (debug)
spring.jpa.show-sql=true